/** Console strings that carry tone — F-CONSOLE-001. Tested against the caregiver ban list. */
export const COPY = {
  whySignIn: ['Keep progress safe across devices', 'Bring cards back after a reinstall', 'Manage plans and billing'],
  kidsNoAccount: "Kids don't need an account — they join with a code.",
  devSignInHint: 'Development sign-in: the account id stands in for a verified session until the Clerk connection lands.',
  clerkPending: 'Sign-in opens with the account connection (coming soon). Until then, the learner app works without an account.',
  cantReach: "Can't reach the console right now.",
  tryAgain: 'Try again',
  noSpaces: "You're not in any space yet.",
  createSpace: 'Create a space',
  writeOnBoard: 'Write it on the board. Students join from Settings → Classes & family → Join a class.',
  oldCodeStops: 'The old code stops working the moment a new one is made.',
  notSyncedYet: 'not synced yet',
  notSyncedWeek: "haven't synced in a week",
  revisitTogether: 'Jamo to revisit together',
  practicedThisWeek: 'practiced this week',
  anchor: 'Stage 1 anchor',
  comingWithPlans: 'Coming with plans',
  capWarning: (used: number, total: number) => `Free plan: ${used} / ${total} students`,
  capReached: 'This class is at the free limit — new students will be asked to check with you.',
  planThisWeek: 'Plan this week',
  publishPlan: 'Publish plan',
  saveDraft: 'Save draft',
  spreadDates: 'Spread dates',
  onePerDay: 'One per day — the later item moved to the next day.',
  draftNeverReaches: 'A draft never reaches a learner. Publishing sends it on their next sync.',
  readoutHint: 'Most recent activity first — not a ranking. "Not ready yet" means the learner has not unlocked that item.',
  archivePlanConfirm: 'Archive this plan? Learners keep what they finished; unfinished items disappear from their list.',
  noPlanYet: 'No plan yet. Pick a few quests, spread the dates, and publish before class.',
  relinkApproveHint: 'Approve only if this learner is with you or you expect this device.',
  relinkNothing: 'Nothing waiting. Requests appear here for 10 minutes after a learner asks.',
  relinkAnotherWay: 'Another way: issue a new rescue code and read it to the learner. The old code stops working.',
  rescueIssued: 'Read this to the learner or their grown-up now — it is shown once.',
  archiveKeeps: 'Keeps everything, stops new joins. You can unarchive later.',
  deleteLearnerWarn: 'Permanent. Removes this learner everywhere: devices, progress, memberships.',
  deleteAskParent: 'Only a parent can delete a learner in this class (consent mode: parent).',
  anonymizeHint: 'Show initials instead of names on the roster and re-link list.',
  consentHint: 'Who consented for the children in this class. School mode lets you delete learner data yourself.',
  billingKidsLine: 'Kids never see billing — this page opens only after the grown-up gate.',
  billingNotConfigured: 'Checkout is not set up yet — prices are still being decided. Nothing was charged.',
  billingCancelled: 'Nothing was charged.',
  billingSuccess: 'Thank you — the plan is active. Learners see it on their next sync.',
  billingPastDue: "A payment didn't go through. Update your card in Manage subscription; learners keep premium for a week.",
  pricePlaceholder: 'price coming soon',
  schoolInviteHint: 'Teachers sign in, enter this code, then create their class — or you create it and assign them.',
  schoolEmpty: 'Invite a teacher with the code, or create a class and assign one.',
  schoolNoLicence: 'No licence yet — each class keeps the free cap of 20 students.',
  schoolNearLimit: 'Close to the licence limit — see billing before the next class fills up.',
  schoolAtLimit: 'At the licence limit — new students will be asked to check with their teacher.',
  schoolLicenceLapsed: 'The licence needs attention. Classes stay readable; students keep Stage 1 either way.',
} as const;

export function allCopyStrings(): string[] {
  return Object.values(COPY).flatMap((v) => (typeof v === 'function' ? [v(16, 20)] : Array.isArray(v) ? [...v] : [v]));
}
